export const cards : {[key: number] : {color: string; number: number , suit: string}} = {
    // ハート（赤）
    0: {color: "red", number: 1, suit: "hearts"},
    1: {color: "red", number: 2, suit: "hearts"},
    2: {color: "red", number: 3, suit: "hearts"},
    3: {color: "red", number: 4, suit: "hearts"},
    4: {color: "red", number: 5, suit: "hearts"},
    5: {color: "red", number: 6, suit: "hearts"},
    6: {color: "red", number: 7, suit: "hearts"},
    7: {color: "red", number: 8, suit: "hearts"},
    8: {color: "red", number: 9, suit: "hearts"},
    9: {color: "red", number: 10, suit: "hearts"},
    10: {color: "red", number: 11, suit: "hearts"},
    11: {color: "red", number: 12, suit: "hearts"},
    12: {color: "red", number: 13, suit: "hearts"},
    
    // ダイヤ（赤）
    13: {color: "red", number: 1, suit: "diamonds"},
    14: {color: "red", number: 2, suit: "diamonds"},
    15: {color: "red", number: 3, suit: "diamonds"},
    16: {color: "red", number: 4, suit: "diamonds"},
    17: {color: "red", number: 5, suit: "diamonds"},
    18: {color: "red", number: 6, suit: "diamonds"},
    19: {color: "red", number: 7, suit: "diamonds"},
    20: {color: "red", number: 8, suit: "diamonds"},
    21: {color: "red", number: 9, suit: "diamonds"},
    22: {color: "red", number: 10, suit: "diamonds"},
    23: {color: "red", number: 11, suit: "diamonds"},
    24: {color: "red", number: 12, suit: "diamonds"},
    25: {color: "red", number: 13, suit: "diamonds"},
    
    // クラブ（黒）
    26: {color: "black", number: 1, suit: "clubs"},
    27: {color: "black", number: 2, suit: "clubs"},
    28: {color: "black", number: 3, suit: "clubs"},
    29: {color: "black", number: 4, suit: "clubs"},
    30: {color: "black", number: 5, suit: "clubs"},
    31: {color: "black", number: 6, suit: "clubs"},
    32: {color: "black", number: 7, suit: "clubs"},
    33: {color: "black", number: 8, suit: "clubs"},
    34: {color: "black", number: 9, suit: "clubs"},
    35: {color: "black", number: 10, suit: "clubs"},
    36: {color: "black", number: 11, suit: "clubs"},
    37: {color: "black", number: 12, suit: "clubs"},
    38: {color: "black", number: 13, suit: "clubs"},
    
    // スペード（黒）
    39: {color: "black", number: 1, suit: "spades"},
    40: {color: "black", number: 2, suit: "spades"},
    41: {color: "black", number: 3, suit: "spades"},
    42: {color: "black", number: 4, suit: "spades"},
    43: {color: "black", number: 5, suit: "spades"},
    44: {color: "black", number: 6, suit: "spades"},
    45: {color: "black", number: 7, suit: "spades"},
    46: {color: "black", number: 8, suit: "spades"},
    47: {color: "black", number: 9, suit: "spades"},
    48: {color: "black", number: 10, suit: "spades"},
    49: {color: "black", number: 11, suit: "spades"},
    50: {color: "black", number: 12, suit: "spades"},
    51: {color: "black", number: 13, suit: "spades"},
    
    // ジョーカー
    52: {color: "black", number: 0, suit: "joker"},
}
export const cards2svg : {[key: number] : string} = {
    0: "ace_of_hearts.svg",
    1: "2_of_hearts.svg",
    2: "3_of_hearts.svg",
    3: "4_of_hearts.svg",
    4: "5_of_hearts.svg",
    5: "6_of_hearts.svg",
    6: "7_of_hearts.svg",
    7: "8_of_hearts.svg",
    8: "9_of_hearts.svg",
    9: "10_of_hearts.svg",
    10: "jack_of_hearts.svg",
    11: "queen_of_hearts.svg",
    12: "king_of_hearts.svg",
    13: "ace_of_diamonds.svg",
    14: "2_of_diamonds.svg",
    15: "3_of_diamonds.svg",
    16: "4_of_diamonds.svg",
    17: "5_of_diamonds.svg",
    18: "6_of_diamonds.svg",
    19: "7_of_diamonds.svg",
    20: "8_of_diamonds.svg",
    21: "9_of_diamonds.svg",
    22: "10_of_diamonds.svg",
    23: "jack_of_diamonds.svg",
    24: "queen_of_diamonds.svg",
    25: "king_of_diamonds.svg",
    26: "ace_of_clubs.svg",
    27: "2_of_clubs.svg",
    28: "3_of_clubs.svg",
    29: "4_of_clubs.svg",
    30: "5_of_clubs.svg",
    31: "6_of_clubs.svg",
    32: "7_of_clubs.svg",
    33: "8_of_clubs.svg",
    34: "9_of_clubs.svg",
    35: "10_of_clubs.svg",
    36: "jack_of_clubs.svg",
    37: "queen_of_clubs.svg",
    38: "king_of_clubs.svg",
    39: "ace_of_spades.svg",
    40: "2_of_spades.svg",
    41: "3_of_spades.svg",
    42: "4_of_spades.svg",
    43: "5_of_spades.svg",
    44: "6_of_spades.svg",
    45: "7_of_spades.svg",
    46: "8_of_spades.svg",
    47: "9_of_spades.svg",
    48: "10_of_spades.svg",
    49: "jack_of_spades.svg",
    50: "queen_of_spades.svg",
    51: "king_of_spades.svg",
    52: "black_joker.svg",
    53: "red_joker.svg",
}